# Generated by Django 5.0 on 2024-03-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gestionCustomer',
        ),
    ]
