# Generated by Django 5.0 on 2024-03-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0002_delete_gestioncustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
            ],
        ),
    ]
