# Generated by Django 5.0 on 2024-03-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacionmodelo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='informacionmodelo',
            name='observacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='informacionmodelo',
            name='comentario',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
