# Generated by Django 5.0 on 2024-02-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banca',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
