# Generated by Django 5.0 on 2024-02-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_destino_credito_user_dias_mora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nro_cuota_pagada',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
